# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0007_auto_20171127_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='reference',
            field=models.TextField(default=''),
        ),
    ]
