# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0008_marker_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marker',
            name='reference',
            field=models.CharField(max_length=500),
        ),
    ]
