# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0006_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
